### ISSUE TITLE
Godoc link doesn't work

### ISSUE THREAD

**Issue by MakotoE** [LdDl/go-egts#1]
Your godoc badge goes to https://godoc.org/github.com/LdDl/go-egts, which is a 404. I suspect it due to your repo not having a license because that is what your page for pkg.go.dev says: https://pkg.go.dev/mod/github.com/LdDl/go-egts?tab=overview.

**Comment by LdDl** [comment]
Yeah...
I've just added MIT License file.
So let's wait for pkg.go.dev updates

**Comment by LdDl** [comment]
link is working now

![image](https://user-images.githubusercontent.com/8864477/85823179-6ae2c000-b785-11ea-885c-e6cec2752a6c.png)
