### ISSUE TITLE
subrecord.SRStateData.Decode() panics with certain input

### ISSUE THREAD

**Issue by MakotoE** [LdDl/go-egts#2]
This test case exhibits two cases that can crash `subrecord.SRStateData.Decode()`.

```
func TestSRStateDataDecodingCrash(t *testing.T) {
	stateData := &subrecord.SRStateData{}
	stateData.Decode([]byte{0})
	stateData.Decode([]byte{1})
}
```

May I suggest doing some fuzz testing on the decode functions? It really helps uncover tricky bugs.

**Comment by LdDl** [comment]
My guess for first step: need to check length of incoming slice of bytes to ensure that there wouldn't be any 'index out of range' (throw error when handling such cases) in any possible Decode() function

WDYT?
